# Generated by Django 2.1.8 on 2019-12-22 05:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('receiver', models.CharField(max_length=20)),
                ('addr', models.CharField(max_length=256)),
                ('zip_code', models.CharField(max_length=6)),
                ('phone_number', models.CharField(max_length=11)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'address_v',
                'verbose_name_plural': 'user_p',
                'db_table': 'df_address',
            },
        ),
    ]
