# Generated by Django 2.1.8 on 2019-11-18 14:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name=' 添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False)),
                ('receiver', models.CharField(max_length=100)),
                ('addr', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=6)),
                ('phone', models.CharField(max_length=11)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': '地址表',
            },
        ),
    ]
